name: ${name}
version: '${version}'
website: ${url}
authors: [${authors}]
main: 'cloud.polars.animations.spigot.AnimationsSpigot'
api-version: '${spigotApiVersion}'
dependencies:
  server:
    EasyArmorStands:
      required: false
      load: BEFORE