name: ${name}
version: '${version}'
website: ${url}
authors: [${authors}]
main: 'cloud.polars.animations.paper.Animations'
api-version: '${paperApiVersion}'
dependencies:
  server:
    EasyArmorStands:
      required: false
      load: BEFORE